spring:
  application:
    name: yfshop-zuul

server:
  port: 8769

zuul:
  routes:
    backend-admin:
      path: /backend/admin/**
      serviceId: yfshop-web-admin
    backend-posts:
      path: /backend/posts/**
      serviceId: yfshop-web-posts