stages:
- build
- push
- run
- clean

build:
  stage: build
  script:
  - /usr/local/maven/apache-maven-3.5.3/bin/mvn clean package
  - cp target/yfshop-config-1.0.0-SNAPSHOT.jar docker
  - cd docker
  - docker build -t 192.168.1.196:5000/yfshop-config .


push:
  stage: push
  script:
  - docker push 192.168.1.196:5000/yfshop-config

run:
  stage: run
  script:
  - cd docker
  - docker-compose down
  - docker-compose up -d


clean:
  stage: clean
  script:
  - docker rmi $(docker images -q -f dangling=true)