version: "3.1"
services:
  yfshop-config:
    restart: always
    image: 192.168.1.196:5000/yfshop-config
    container_name: yfshop-config
    ports:
    - 8888:8888
    networks:
    - config_network

networks:
  config_network: